Generate CSS file when make run and fix dupe variable declaration
25077667/facebooc pull request #12
Opened 2022-05-30 17:47 UTC by charles1046

2022-05-30 23:26 UTC, 25077667 requested changes
Please remove the duplicated $(EXEC) tag.

2022-05-30 23:26 UTC, 25077667 commented on Makefile
> +run: $(EXEC) html-updater $(EXEC) gen-css
The $(EXEC) is duplicated.

2022-05-31 02:26 UTC, charles1046 commented
Updated

2022-05-31 02:32 UTC, 25077667 reviewed
Ok, thanks.

2022-05-31 02:32 UTC, merged