Refactor handlers
25077667/facebooc pull request #24
Opened 2022-06-10 13:29 UTC by charles1046

I refactored handlers and tried to manually solve merge conflict.
But due to file creations, I'm unable to fully solve the conflict.

2022-06-10 13:32 UTC, charles1046 commented
`src/http/cookies.c`: Typo. Not really a conflict.
`src/facebooc_server.c`: Handlers are moved to separated source files.
`src/server.c`: Handler of handlers is moved to a separated source file.

2022-06-10 13:53 UTC, charles1046 commented
Fixed 404 after liking.

2022-06-10 13:58 UTC, charles1046 commented
@charles1046
[Refactor database finalize statement](https://github.com/25077667/facebooc/pull/24/commits/2cc6027dd55be8cf7679705999e933e48c9f5dd1)

2022-06-10 14:14 UTC, 25077667 requested changes
Please see the comments. Thanks!

2022-06-10 14:14 UTC, 25077667 commented on src/server.c
> +	if(n_read > 0) {
Use else if here.

2022-06-10 14:14 UTC, 25077667 commented on src/handler/handler.c
> +	char* handling_type = get_handling_type(request);
I prefer to use "routing path".

2022-06-12 14:13 UTC, charles1046 commented
Updated.

2022-06-12 15:08 UTC, 25077667 requested changes
Please see the comments.
Thanks.

2022-06-12 15:08 UTC, 25077667 commented on src/handler/handler.c
> +static inline void add_handler(Hash_map* handlers, char* handling_name, Handler handler) {
We should not add handlers here.
Each server has a set of handlers, and the facebooc server is a derived class of a server.
We could register some handlers into a base class, but not modify it directly.

Please refer to Open-closed principle.

2022-06-14 03:06 UTC, 25077667 reviewed
Viewed.

2022-06-19 13:26 UTC, closed without merging